### ISSUE TITLE
Firmware 05 only blinks red, not green or orange

### ISSUE THREAD

**Issue by weliem** [50ButtonsEach/flic2lib-android#10]
We ordered some buttons that happened to have version 05 of the firmware. We noticed that although they worked fine, the led always blinks red. Our other buttons that are on version, blink green or orange after pairing succeeds.

We suspect this is because of the firmware version. After we updated the button from 05 to 08, it also started to blink green/orange.

Can you confirm this? Or is there some other reason for not blinking green/orange? Is there a list of changes per firmware version published somewhere?

**Comment by Emill** [comment]
Yes, that's correct. The LED colours were improved after revision 5.
We don't have a public change list, but for some new firmware features, it's mentioned at https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification when they were introduced.
