### ISSUE TITLE
Using a lower minSdkVersion

### ISSUE THREAD

**Issue by arlomedia** [50ButtonsEach/flic2lib-android#13]
My app has a minSdkVersion of 15, and the flic2lib requires version 19. I've added

`<uses-sdk tools:overrideLibrary="io.flic.lib, io.flic.flic2libandroid" />`

to my AndroidManifest file, and hidden all the Flic functions in my app with conditionals like

`if (android.os.Build.VERSION.SDK_INT >= 19)`

This works fine when building, running and distributing the first-generation flic library. And with this second-generation library, I can build and run my app locally, but when I try to generate a signed APK for distribution, the build stops with this error:

`io.flic.flic2libandroid.L2CapUtils: can't find referenced method 'android.bluetooth.BluetoothSocket createInsecureL2capChannel(int)' in library class android.bluetooth.BluetoothDevice`

I see that `createInsecureL2capChannel()` requires SDK 19, but this should be ignored. Is there something else I need to do to with the library setup to make this work, or does the library need an update to allow this to work?

(I also tried annotating all my Flic functions with `@TargetApi(19)`, but that didn't make a difference.)

Update: I was able to build a release APK by adding this to my proguard-rules file:

`-dontwarn io.flic.**`

**Comment by Emill** [comment]
You should have the compileSdkVersion and targetSdkVersion at 29 or later. You could set minSdkVersion to whatever you want, but if you set it to less than 19, you must be sure not to invoke the library (as it won't work in that case).

**Comment by arlomedia** [comment]
I'm doing all those things, but the app wouldn't build with `minifyEnabled true` unless I added the dontwarn flag for Proguard. Maybe supporting such old Android versions as I do is rare enough that it's not worth doing anything about, but perhaps this workaround could help someone else in my situation.
