### ISSUE TITLE
button.connect() doesn't appear to work

### ISSUE THREAD

**Issue by nckshr** [50ButtonsEach/flic2lib-android#14]
I am trying to reconnect to previously paired buttons on app startup. Connecting to new buttons works fine (I get click events and so on). 

However, when I try registering listeners for perviously paired buttons, it doesn't seem to work.
Currently, my code is as follows:
```java
Flic2Manager.initAndGetInstance(getApplicationContext(), new Handler());
for(Flic2Button button: Flic2Manager.getInstance().getButtons()){
    //this is a button previously paired
    Log.d("Flic2", "Found already paired button ("+button.getBdAddr()+") in state " + button.getConnectionState() + ". connecting...");
    button.connect();
    String bdaddr = button.getBdAddr();
    Log.d("Flic2","registering listeners for button ("+button.getBdAddr()+")");
    button.addListener(myListener);
}
```
When I run this code, I get the following output:
```
Found already paired button (80:E4:DA...) in state 0. connecting...
registering listeners for button (80:E4:DA...)
```

However, the callback methods (onConnected, onButtonSingleOrDoubleClickOrHold, etc) in  myListener are never firing. The addListener function seems to work just fine in the "onCompleted" callback of the scanning process... am I doing something wrong? Do I need to put the addListener call in some sort of connection callback, or am I ok to do it as I have here? If I have missed something in the documentation, my apologies, please point me to the correct page and I will do some reading.

**Comment by Emill** [comment]
That should work. Do you see something Bluetooth related in logcat?
Also, does the LED light up on the button when you press it? (how and with what colour?)

What Android device do you have by the way?

**Comment by nckshr** [comment]
I have a Samsung SM-T515 tablet running Android 10 (kernel 4.4.177-19580935). 

Are there any filters that might help me identify relevant logcat messages? I could also potentially get the bluetooth HCI snoop logs if needed.

When I press the flic2 button, it quickly blinks green once.

**Comment by Emill** [comment]
Green means connected. Is the button connected to something else than your app?
You shouldn't need to use a filter. It should be easy to see what is Bluetooth related.

We also have a logger interface built-in to the library. You can pass a `LoggerInterface` to the `setLogger` method. This should give the relevant info.

**Comment by nckshr** [comment]
Ah, I think I've identified the issue. I am utilizing the Flic2 library within a service thread, so I believe after this call
```java
if(Looper.myLooper() == null) Looper.prepare();
Flic2Manager f2manager = Flic2Manager.initAndGetInstance(myService.getApplicationContext(), new Handler());
```
I need to get everything set up (reconnect buttons, start scan) and then call
```
Looper.loop();
```
so that the Handler actually gets the messages from callbacks & button events. It's strange, I know had it there when connecting the first time, but somewhere along the way it must have gotten deleted. An important note for anyone using the library not on the main thread is to make sure you loop before your thread dies and can't receive events!

Sorry for the trouble, looks like in the end it was user error and things seem to be working now, I'll keep you posted if I start seeing issues again but I think that fixed it. Thanks for your help!

**Comment by Emill** [comment]
Yes that definitely explains the issue. Although I generally strongly suggest to keep the number of threads down in an app, to avoid complexity and possible race conditions.

**Comment by nckshr** [comment]
Thanks for the advice. Currently I just have a single thread that manages all the flic button stuff (connects to existing buttons, initiates a scan and then loops). Though now I am curious - does the flic2manager spawn it's own thread to listen for button events, then notifies the corresponding listeners? Is the callback run in the same thread as the Handler I give when initializing the manager, or is it something else? Just want to make sure I understand what is happening so I can manage threads accordingly. Sorry if this is the wrong place to ask this question, let me know if you guys have a forum or stack exchange set up for this sort of thing.

**Comment by Emill** [comment]
We have a developer forum here:
https://community.flic.io/category/8/developers

The library does not spawn new threads, except for a few I/O scenarios where this is then completely hidden from the user's point of view. Everything else runs on the same thread as the one the Handler's running on, i.e. all logic in the library as well as all callbacks. Therefore if you run your own logic on the main thread (for example if you have a UI running on the main thread), I recommend you to run this library on the main thread too, to avoid race conditions and other kinds of complexity.
