### ISSUE TITLE
How to show the Foreground Service only I have a button connected?

### ISSUE THREAD

**Issue by LucasMonteiro1** [50ButtonsEach/flic2lib-android#15]
https://github.com/50ButtonsEach/flic2lib-android#background-execution

**Comment by Emill** [comment]
Hi. You must yourself keep track of when you have a button or not.

Start a Foreground Service as described when you connect your first button.

Then you basically call https://developer.android.com/reference/android/app/Service#stopForeground(boolean) with `removeNotification` set to `true` when you have no buttons connected anymore.

You should cache the `notification` object to be reused every time you call `startForeground`.
