### ISSUE TITLE
Disconnect status on buttons/ Already connected

### ISSUE THREAD

**Issue by Saurabh-Sawla** [50ButtonsEach/flic2lib-android#16]
Dear Team,

Thanks the FLIC button and its SDK are really useful. However, in our application for using the FLIC button we need to have 2 things which are not really related to any specific SDK. Would it be possible for you to let us know -

1. If the disconnect status on buttons can be determined when the Flic button is not in range and how it can be detected again. This is something that we could not get from the library.
2. Also, how would we be able to establish if a button is already connected to another device, as it can be scanned but disconnected.

If you can provide response to these queries that would be really great.

Regards,
Saurabh

**Comment by Emill** [comment]
1. You can get the status using getConnectionState() on the button. The callbacks on your button listener will also notify you when the state changes.
2. When you perform a scan, you will get the result RESULT_FAILED_BUTTON_ALREADY_CONNECTED_TO_OTHER_DEVICE when this happens. The button must be pressed and held at least 6 seconds however, otherwise it will not advertise this info.

Let me know if I misunderstood your questions.

**Comment by Saurabh-Sawla** [comment]
Let me check for item#1. Actually we are using the react native SDK currently.

For the question 2, I would like to explain via an example -

- Let's consider there are 2 devices A and B to which we are attempting to add the Flic button to.
- I scanned the button into device A and then disconnected it manually from the settings.
- Now, I scanned the button into device B and then attempt to connect the Flic button in device A again.

I want the device A to tell me that Flic button is already connected. Is it possible?

**Comment by Emill** [comment]
> I want the device A to tell me that Flic button is already connected. Is it possible?

No that won't work. The Flic button doesn't advertise anything while connected (unless the user keeps the button held for at least 6 seconds), so that can't be detected. You could potentially set up some own LAN or cloud solution where you send this information to other devices running your app.

**Comment by Saurabh-Sawla** [comment]
Ok Thanks. Let us check the response to your question for the item#1 for the disconnection state.
