### ISSUE TITLE
Migrate from JCenter to MavenCentral (or another provider)

### ISSUE THREAD

**Issue by kohenkatz** [50ButtonsEach/flic2lib-android#17]
JFrog announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:

March 31st: JCenter stopped accepting new uploades
May 1st: JCenter API and web UI will no longer be available
February 1st, 2022: JCenter will stop allowing downloads

Android Studio warns developers that "JCenter is at end of life" and prompts them to remove `jcenter()` from their `build.gradle` files.

Moving to MavenCentral is fairly easy - see https://central.sonatype.org/publish/

**Comment by andrblum** [comment]
Hello, 

Android Developer is also showing the warning that JCenter is going out of service.
I hope that the library is moved to the Maven repository before the JCenter is down.

Thank you for your help

Best regards
Andreas

**Comment by Emill** [comment]
I think we will rather use JitPack. Seems way easier to use and maintain?

**Comment by andrblum** [comment]
Thanks for your answer.
As long as it is usable from Android Studio, the repository should not matter.
(_I have no experience with JitPack._)

**Comment by jdegger** [comment]
Any progress on this?

We got an issue here: https://github.com/X-Guard/react-native-flic2/issues/27

JCenter is already not serving it anymore?

---
Seems offline indeed: https://jcenter.bintray.com/io/flic/flic2lib-android/1.1.0/flic2lib-android-1.1.0.aar

**Comment by Emill** [comment]
I modified the README with instructions on how to use JitPack instead, which seems to be working fine. It automatically builds and hosts the needed files directly from the GitHub repo, which I think is pretty nice.

**Comment by andrblum** [comment]
Your instructions worked perfectly.
Thank you very much! :-)
