### ISSUE TITLE
Button getting auto disconnected and name getting changed to ����� after it.

### ISSUE THREAD

**Issue by Ravi8421** [50ButtonsEach/flic2lib-android#18]
I have integrated multiple flic buttons in one app but for the specific instance of a button, it is getting disconnected automatically and after re-connecting it the name of the button gets encrypted like ������.

I can't found any reason for auto disconnection, I have tried with multiple flic2 devices, but no luck.

what can be the reason behind it? 
multiple (around 3) flic2 devices at the same time could be the issue?

**Comment by Emill** [comment]
What's the content of the status variable here? https://github.com/50ButtonsEach/flic2lib-android/blob/7f7848b1d27acb2457c759c7f2caed2cd077a1f0/flic2lib-android/src/main/java/io/flic/flic2libandroid/Flic2Manager.java#L1096

If you have a "steps to reproduce" to get that name error, that would be good.

**Comment by RaviKoradiya** [comment]
I can't find any useful log there.
1. I have integrated flic1 library as well along with flic2, can it cause the disconnection issue for flic2?
2. can I use the flic grabber from flic1 library to pair/connect flic2?
3. what is the chance of a hardware issue causing the disconnection automatically?

**Comment by jdegger** [comment]
We also basically reported the same issue a while back here: https://github.com/50ButtonsEach/flic2lib-android/issues/4

We never fully resolved it

**Comment by Emill** [comment]
You can either set a breakpoint when you run the code in android studio, or use the LoggerInterface to get logging (see the API docs).

1. Seems not so likely. If you have many connections you could potentially reach the maximum number of connections supported by the device. Another possibility would be that the Bluetooth controller in the device is bad at handling multiple connections.
2. No.
3. If the Flic button reboots for any reason, it should flash red briefly (very short) a few times. Then you could see a disconnect due to this. But otherwise it happens all the time that Bluetooth connections time out due to radio interference or similar.

**Comment by alex49881** [comment]
I have a similar issue. The name of one of the buttons in my app unexpectedly changes value to ������.  
Has anyone solved it?

**Comment by Emill** [comment]
We are about to release a new firmware that will fix this. The issue happens if you take out the battery and insert it again.

**Comment by alex49881** [comment]
It is strange because I have not replaced the battery of any button.

**Comment by Emill** [comment]
Maybe the battery contact is glitchy or something on your button so that the button reboots. You will see when this happens since the button blinks red three times quickly whenever it's booting.

**Comment by alex49881** [comment]
I have been testing these days the 4 buttons that my application uses, and at some random moment they all end up resetting and therefore causing the name value problem.
Is this caused by a hardware failure? Is this normal button behavior?

**Comment by alex49881** [comment]
I thought it was a battery failure causing the button to reset, but I've tried all four buttons and at some random time each one resets.

I don't think the 4 buttons have a battery failure.

What hardware problem can cause these reboots?

**Comment by Emill** [comment]
The button will also reboot after a firmware upgrade.
A button could probably reboot randomly if it has low battery as well.
