### ISSUE TITLE
Nickname field

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/flic2lib-android#2]
Hi,

We are seeing the differences between iOS and Android when looking at the name/nickname field.

iOS seems to implement a special `nickname` so you do not have to change the actual internal BT name of the button. However on iOS there is no method to change this name (https://github.com/50ButtonsEach/flic2lib-ios/issues/5).

On Android there _is_ a method to change the name, but there is no nickname. 

Could the nickname be added here too or would you recommend just using the name? Are there limits on the name field?

Thanks,
Jesse

**Comment by Emill** [comment]
The name here is the same thing as the nickname in the iOS lib.

**Comment by jdegger** [comment]
Alright, the documentation on iOS implies that there is a difference between name and nickname:
- the name is the BT name used for pairing etc.
- the nickname is used as identification across apps

So when changing the name on Android, the BT name is not changed?

**Comment by Emill** [comment]
The BT name is never changed. It will be unique to every button.

The nickname or name in this lib is a custom name that can be read and written at any time, for example "Living room".

**Comment by jdegger** [comment]
Alright, thanks 👍
