### ISSUE TITLE
android 12 new Bluetooth permission updates

### ISSUE THREAD

**Issue by orcuns** [50ButtonsEach/flic2lib-android#20]
Are you going to update your sdk with the latest android 12 Bluetooth permission updates?
Do we still need to ask for Location permission on android 12?

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

Edit: Or maybe only ACCESS_COARSE_LOCATION is enough?

**Comment by Emill** [comment]
BLUETOOTH_SCAN and BLUETOOTH_CONNECT are the new permissions that should be used. Location is not needed anymore. We have not been able to test this yet since our Pixel phones we have at the office have not got the Android 12 update yet. We'll change when that happens.

**Comment by Emill** [comment]
Could you try the latest release?

**Comment by orcuns** [comment]
> Could you try the latest release?

with v1.3.1?

**Comment by Emill** [comment]
Yes

**Comment by orcuns** [comment]
I upgraded from v1.1.0 to v1.3.1. I can't connect the button anymore. `onComplete` result returns 8 after some time later. No idea what's wrong.  

I read `API versioning and manifest permissions` part in ReadME part. I'd like to know, do we still need to call `ACCESS_FINE_LOCATION` in API 31?

**Comment by Emill** [comment]
```java
    /**
     * Failure that happens when the system pairing dialog is not accepted.
     */
    int RESULT_SYSTEM_PAIRING_DIALOG_NOT_ACCEPTED = 8;
```

There should be a popup from the system where you shall press "Pair & Connect" in order to pair. Do you see such a dialog?

`ACCESS_FINE_LOCATION` is not needed anymore in API 31.

**Comment by orcuns** [comment]
Yeah I see that pop-up! Should we click on that?

**Comment by Emill** [comment]
Yes.

**Comment by orcuns** [comment]
ok It works after we pair. Thanks a lot!
