### ISSUE TITLE
Unable to read button error

### ISSUE THREAD

**Issue by dineshanchetty** [50ButtonsEach/flic2lib-android#24]
hi there

we are connecting the button via an Ionic front end and are able ot register the device, but are having issues with reading the actions - please see below response
![image_2022_10_12T12_58_23_684Z](https://user-images.githubusercontent.com/46397632/195511147-61561cc6-f05f-4eff-aece-a3241fe32fe0.png)

**Comment by Emill** [comment]
I'm not sure what you're trying to do. Are you using this library at all?

**Comment by dineshanchetty** [comment]
hi -  
we are using the library referred to in this post -  https://community.flic.io/topic/17858/ionic-development-with-flic-2?_=1665646982298

**Comment by Emill** [comment]
If you want to implement the protocol yourself then you should follow https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification.

But I really recommend that you call this flic2lib-android library instead from your ionic code.

**Comment by dineshanchetty** [comment]
hi, it not possible to call android native functions directly from ionic, hence the need for the plugin, we are able to register the device successfully, but are having problems only with reading the actions.

**Comment by Emill** [comment]
If ionic can't call native functions, then how does the plugin call the native BLE functions? You should be able to do the same, so instead of calling the BLE API directly, call the methods in this library instead.
