### ISSUE TITLE
how to end the background service

### ISSUE THREAD

**Issue by hooli01** [50ButtonsEach/flic2lib-android#28]
I wanna give the option to the user to end the background service. 
But all my efforts are in vain ... 

`ActivityManager am = (ActivityManager) getSystemService(Activity.ACTIVITY_SERVICE);
        am.killBackgroundProcesses("****.*****.****");
        super.onDestroy();

        int id= android.os.Process.myPid();
        android.os.Process.killProcess(id);`
doesnt seem to end it...

Does anyone know how to do this?
thanks in advance

**Comment by Emill** [comment]
Hi. There is no background service running in this library.
Do you mean an application-defined Foreground Service, as explained as should be added in the Readme? I.e. as this example: https://github.com/50ButtonsEach/flic2lib-android-sample/blob/master/app/src/main/java/flic/io/flic2androidsample/Flic2SampleService.java.

In that case, see https://developer.android.com/guide/components/foreground-services#remove-from-foreground how to remove a Service from Foreground. Or see https://stackoverflow.com/a/20857343 how to also stop it.

**Comment by hooli01** [comment]
yes sorry that is what i meant..
i think i understand it now...
thanks
