### ISSUE TITLE
Change of permission to don't allow crashes framework

### ISSUE THREAD

**Issue by creative-intersection** [50ButtonsEach/flic2lib-android#29]
Any time a user has a button connected and then goes and changes the permission to don't allow results in a crash/ killing of app. In Android Studio it just shows the app as dead. There is no error in the logcat for show only selected application and there is not much showing when looking at the no filters. It does say "Scheduling restart of crashed service" as we have a start sticky foreground service in our app.

Steps to reproduce: Scan and connect a button -> home out of app and open the app's settings -> change to Don't allow Nearby devices permission -> app instantly crashes. 

Is this crash coming from your framework? Or is this how Android is now handling the permission change by Killing the app due to permissions revoked? Note we first became aware of this issue after some users reported issues after installing a security update on their device which appears to have reset their previous selected permissions. This resulted in a similar situation to the steps to reproduce mentioned above.

**Comment by Emill** [comment]
As I have understood, this is the "solution" Android handles permission revokes. They want to make sure for the programmer that if you ever did "if (has permission) { do stuff }" then, once in "do stuff" you can be sure that you have the permission. Please let me know if you have a better idea how to handle the problem you are describing.

The device you mentioned that had the security update, was it a "vanilla" Android device such as Google Pixel, or another Android device where the manufacturer could have added their own behaviour?
