### ISSUE TITLE
Provide click action

### ISSUE THREAD

**Issue by moopat** [50ButtonsEach/flic2lib-android#3]
I couldn't find a way to simply provide a click action to the Flic app. If this is possible please let me know, otherwise please consider this a feature request:

I'd like to expose functionalities from my app that can be triggered by the click of a Flic button. This would typically work on a broadcast basis. As user I can already create a "Send Intent" action and trigger it on the click of a button, but I think it's unacceptable to ask a user to enter the correct action, data, package etc just to make the Flic button trigger an action in my app. What I would like is that while my app is installed, the actions it provides are listed in the Flic app.

From the documentation I gather that I can bind a button to my app (which will then need to run in the foreground at all times and require the location permission), but I'd much rather let the Flic app handle the button communication and also allow the user to decide what the button does when: one click dismisses the alarm in my app and starts the coffee maker, two clicks launch the built-in fart generator and a long click dims the light.

**Comment by oKcerG** [comment]
Any update on this ?

I want to integrate Flic in a future app but I don't want to deal with the low level communication, it isn't user-friendly or dev-friendly.

Something like an action plugin in Tasker would be nice : https://tasker.joaoapps.com/plugins-intro.html / https://www.twofortyfouram.com/developer/ / https://www.twofortyfouram.com/developer/

Maybe just reuse the Locale API with ACTION_EDIT_SETTING and ACTION_FIRE_SETTING

**Comment by Emill** [comment]
Most of our partners want to have Flic support directly in their app and not force their users to download the Flic app.
Note that a button can be connected to multiple apps at the same time so you can do something in your app on click and something in the Flic app on hold.
