### ISSUE TITLE
Permission Issue on API-Level 33

### ISSUE THREAD

**Issue by harrypotter06** [50ButtonsEach/flic2lib-android#30]
Hello,

with Android 12 (API 31), we had no issues with the Library. Scan for new buttons work fine.
On Android 13 (API 33) we got a error, if scan new Flic2Button:

System.Exception: Need android.permission.BLUETOOTH_CONNECT

This Error is in GattService registerClient.

The App was build für Android 12 (API 31)

In AppManifest i set this permissions:

```
<uses-permission android:name="android.permission.BLUETOOTH"  />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"  />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"  />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"  />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
<uses-permission android:name="android.permission.INTERNET"/>
```
I thik is any changes on API 33?
Whats the solution to Fix it?

**Comment by JB-CHAUVIN** [comment]
BLUETOOTH_SCAN/BLUETOOTH_CONNECT not granted. Please call 'Activity.requestPermissions(String[], int') first.

error for me on Android 33...

**Comment by Emill** [comment]
Please follow the permissions part of the tutorial at https://github.com/50ButtonsEach/flic2lib-android#scanning-for-new-buttons.

**Comment by JB-CHAUVIN** [comment]
@Emill , which part of the tutorial should we read ? 
It's not working... on Android 33.

**Comment by Emill** [comment]
What exactly is not working? If you target Android 13 you need to read the parts saying "Android 12 or higher".
Did you acquire permissions at runtime as stated in the tutorial?
