### ISSUE TITLE
Keep getting timeout on button connect

### ISSUE THREAD

**Issue by AbstractionsAs** [50ButtonsEach/flic2lib-android#32]
Trying to make flic2lib work, but whenever I try to pair a button:

- It is immediatly discovered
- Nothing happens for a while
- It completes with RESULT_FAILED_CONNECT_TIMED_OUT 

I'm having a hard time figuring out the problem. Testing this on a brand new Pixel 8 Pro.
Bluetooth works for everything else on the phone.
All permissions are granted.

**Comment by Emill** [comment]
Does it work in the Flic app?

**Comment by AbstractionsAs** [comment]
@Emill Just installed the flic-app, and no, it doesn't. Same timeout.
However, the flic app works on an older Huawei P30 Pro. Going to try debugging my app on that one as well.

**Comment by AbstractionsAs** [comment]
@Emill Doesn't seem like it works with the lib on either phone, but it could be that it would work on the older phone with a lower target SDK. Checking various combinations...

**Comment by AbstractionsAs** [comment]
@Emill Forgot to say: If it's paired to the old phone when I try to connect via the lib I get error code 5 instead of 6. If I disconnect it from the old phone it goes back to error 6

**Comment by AbstractionsAs** [comment]
Ok, So that's confirmed. It works on the P30 when built against SDK 31. Pixel always fails. Seems there was a change somewhere that breaks the library.

**Comment by Emill** [comment]
Could you maybe have too many active Bluetooth connections on your phone? (7 was the max last time I checked in Android)
Tried to reboot the phone?

If it doesn't work in the Flic app either, please try to pair and then use the Submit Bluetooth Log button at the bottom of the Help & Feedback section.

**Comment by AbstractionsAs** [comment]
@Emill No, It doesn't work on any of the phones I've tested with when i build against SDK 34. When I build against SDK 31 it works on older phones, but not the new one.

Booting the phone actually helped, at least with the SDK31 build. I'm going to try a new SDK34 build tomorrow, but when I tried that it didn't work on any phone beore..
