### ISSUE TITLE
Verifier check failed

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/flic2lib-android#33]
Hi,

We are seeing, for the first time in years, error code 2 where the verifier check fails.

Can be explained when this happens and how to remedy? It happens with multiple buttons and also after full reboot.

**Comment by Emill** [comment]
Can you post the full debug log output from the session? (See LoggerInterface how to get log events)

**Comment by jdegger** [comment]
No sorry, this was with a customer remotely. We have never encountered it and were just wondering why or how this could happen. What possible reasons there are for this error.

**Comment by Emill** [comment]
Should not happen in case the Bluetooth stack works correctly and delivers the data correct bit by bit.

See `FULL_VERIFY_FAIL_REASON_INVALID_VERIFIER` in https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification for details.
