### ISSUE TITLE
Sdk crashes my app when an attempt to scan for buttons is fails

### ISSUE THREAD

**Issue by CodyTroopDev** [50ButtonsEach/flic2lib-android#35]
Recreation steps:

- ensure no Flic buttons are available to pair
- call the startScan method from a Flic2Manager
- app crashes after several seconds

The onComplete override I give to the scan appears to be called without a button, which is a required argument leading to an error like this: `Parameter specified as non-null is null: method com.example.repository.ExternalButtonRespositoryImpl$scanForButtons$1.onComplete, parameter button`

**Comment by Emill** [comment]
Per the documentation:

```java
    /**
     * Called when the scanning has finished for any reason, unless scanning was explicitly stopped.
     *
     * @param result result code, see {@link Flic2ScanCallback} and {@link Flic2ButtonListener} for a list of codes.
     * @param subCode a subcode
     * @param button if {@link #RESULT_SUCCESS}, the button object that is now both connected and ready
     */
    void onComplete(int result, int subCode, Flic2Button button);
```

so if it did not complete successfully, then `button` will indeed be `null`. It seems you have added some extra check in your code that throws an exception in case `button` is `null`.

**Comment by Emill** [comment]
Maybe you have some framework running that requires you to annotate the parameter with `@Nullable` or something in your implementation class of the interface.

**Comment by CodyTroopDev** [comment]
Hey, thank you for responding so quickly.  Yeah, my implementation is in Kotlin, and it seems I just needed to be more careful with my types.  

Updating my implementation to account for nulls worked just fine, and I'm a bit embarrassed I didn't consider changing my method signature to begin with.

Thanks again!

**Comment by Emill** [comment]
Just want to check... Was the incorrect method signature auto generated by some autocomplete tool in Android Studio, or was it a manual mistake?

**Comment by CodyTroopDev** [comment]
No, the auto-implement works just fine and handles the null, but I wrote it by hand the first time and wasn't aware of the differences between Kotlin and Java in how they deal with nullability.  So I mostly just read the interface wrong.

**Comment by Emill** [comment]
Thanks!
