### ISSUE TITLE
Does not allow precise location permission

### ISSUE THREAD

**Issue by irinebthayil-1** [50ButtonsEach/flic2lib-android#36]
Once I add the grade dependency for the button, it does not allow me to ask for precise location on Android 12+. My app requires precise location from the user, what could be a fix for this?

**Comment by Emill** [comment]
This scenario is handled in the readme: https://github.com/50ButtonsEach/flic2lib-android?tab=readme-ov-file#api-versioning-and-manifest-permissions:

> When targeting API 31 or higher and the app needs the ACCESS_FINE_LOCATION permission for any purpose other than Bluetooth scanning, add the following line directly inside the <manifest> tag:

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" tools:remove="maxSdkVersion" />
```

**Comment by irinebthayil-1** [comment]
Thank you for the prompt response.
