### ISSUE TITLE
Button name after scanning

### ISSUE THREAD

**Issue by wesdewitte** [50ButtonsEach/flic2lib-android#4]
When i scan for a button and connect with one. With some buttons i don't get the correct name. Like this:

![Screenshot 2020-02-20 at 16 35 46](https://user-images.githubusercontent.com/3693012/75012747-f4564e80-5482-11ea-83fe-9b2aefb1271f.png)

Then i reset then name again and it goes well. But then if i forget the button and then rescan and connect again, its again the same as in the img. It's weird because not all buttons have this behaviour. But the buttons that encounter this problem are consistent at it.

**Comment by Emill** [comment]
Hi. How do you get javascript events?

**Comment by wesdewitte** [comment]
From java whe send it as following:
![Screenshot 2020-02-21 at 08 31 14](https://user-images.githubusercontent.com/3693012/75013503-b4906680-5484-11ea-93bf-07bbcddf8fae.png)

And then in our javascript we set it as following: 
![Screenshot 2020-02-21 at 08 32 09](https://user-images.githubusercontent.com/3693012/75013534-c245ec00-5484-11ea-944d-41adaff4c2dc.png)

**Comment by wesdewitte** [comment]
This code can be found in here https://github.com/X-Guard/react-native-flic2

**Comment by Emill** [comment]
Do you "reset the name" by setting the name to an empty string while being connected?

**Comment by wesdewitte** [comment]
No if i set the name to something like "Test button". It goes well, if a click the button i see that the name has been changed to "Test button". But like i said not all buttons have this behaviour

**Comment by Emill** [comment]
So these steps should reproduce the issue?
1. Set name to "test button" while being connected.
2. Forget button.
3. Scan and pair the same button.
4. Sometimes the name is now incorrect?

**Comment by wesdewitte** [comment]
Yes how i test it is al following:
 

1. Set name to "test button" while being connected.
2. Force an event like click to see if name has been changed correctly - yes it does.
3. Forget the button.
4. Scan and pair the same button.
5. Name is not correct.

But then again, there are only a few buttons that have this behaviour. But the buttons that have this behaviour always have it.

**Comment by Emill** [comment]
Is the Flic app (or any other app) connected to the button at the same time or not?

**Comment by wesdewitte** [comment]
The flic app is running in the background but is not connected to that specific button or any other app

**Comment by Emill** [comment]
Could you set a breakpoint or debug log print the parameters to this function in Flic2Button.java:
```private void onGotName(long timestampUtcMs, String name) {```
which should be called after you set the name. I'd like to know the contents of the parameters.

**Comment by wesdewitte** [comment]
It seems like onGotName is never fired
![Screenshot 2020-02-21 at 11 00 08](https://user-images.githubusercontent.com/3693012/75024300-73568180-5499-11ea-9c25-4ccfb2e63bec.png)
![Screenshot 2020-02-21 at 11 00 19](https://user-images.githubusercontent.com/3693012/75024306-76ea0880-5499-11ea-8774-7b8be07aa563.png)

**Comment by wesdewitte** [comment]
Oke got it now : 
![Screenshot 2020-02-21 at 11 52 05](https://user-images.githubusercontent.com/3693012/75028485-9df80880-54a0-11ea-88b1-288f71a84221.png)
 is this the info you're looking for?

```
           if (!name.equals(Flic2Button.this.name)) {
                Flic2Button.this.nameTimestampUtcMs = 0;
                Flic2Button.this.name = name;
                manager.database.updateName(Flic2Button.this);
                listener.onNameUpdated(Flic2Button.this, name);
            }
```

This is never fired in onGotName because Flic2Button.this.name is already set to the new in:

```
    public void setName(final String name) {
        if (name == null) {
            throw new NullPointerException();
        }
        manager.runOnHandlerThread(new Runnable() {
            @Override
            public void run() {
                if (unpaired) {
                    return;
                }

                Flic2Button.this.nameTimestampUtcMs = System.currentTimeMillis();
                Flic2Button.this.name = name;
                manager.database.updateName(Flic2Button.this);
                if (Flic2Button.this.isConnected) {
                    Session s = Flic2Button.this.currentGattCb.getSession();
                    if (s != null && s.isEstablished()) {
                        s.sendSetName();
                    }
                }
            }
        });
    }
```

**Comment by Emill** [comment]
Yes it looks fine. So now when you forget the button and re-pair it, do you see that in the `FullVerifyResponse2` constructor, it sets `name` to garbage?

**Comment by wesdewitte** [comment]
hmm really weird i wanted to see the outcome from the FullVerifyResponse2. But the name got set correctly this time and now i can't reproduce it anymore. I will keep you up to date when i see it again. For now i will close this issue.
