### ISSUE TITLE
Register GATT client, MAX client reached: 32

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/flic2lib-android#5]
Hi, we're seeing the error `Register GATT client, MAX client reached: 32` on some phones.

The following log shows us what's happening:

```
02-21 10:59:45.776  6862  9476 D BtGatt.ContextMap: add() - appUid: 10271, appName: our.app.bundle.name
02-21 10:59:45.777  6862  7491 I bt_stack: [INFO:gatt_api.cc(955)] GATT_Register 57a1b35d-d97c-4818-bc5b-3d9777f59fb0
02-21 10:59:45.777  6862  7491 E bt_stack: [ERROR:gatt_api.cc(997)] can't Register GATT client, MAX client reached: 32
02-21 10:59:45.777  6862  7491 E bt_btif : GATT Register Failed for client, MAX Interface reached!
02-21 10:59:45.777  6862  7491 I bt_stack: [INFO:gatt_api.cc(955)] GATT_Register 57a1b35d-d97c-4818-bc5b-3d9777f59fb0
02-21 10:59:45.777  6862  7491 E bt_stack: [ERROR:gatt_api.cc(997)] can't Register GATT client, MAX client reached: 32
02-21 10:59:45.777  6862  7491 E bt_btif : GATT Register Failed for client, MAX Interface reached!
02-21 10:59:45.777  6862  7491 I bt_stack: [INFO:gatt_api.cc(955)] GATT_Register 57a1b35d-d97c-4818-bc5b-3d9777f59fb0
02-21 10:59:45.777  6862  7491 E bt_stack: [ERROR:gatt_api.cc(997)] can't Register GATT client, MAX client reached: 32
02-21 10:59:45.777  6862  7491 E bt_btif : GATT Register Failed for client, MAX Interface reached!
02-21 10:59:45.777  6862  6949 D BtGatt.ContextMap: remove() - uuid: 57a1b35d-d97c-4818-bc5b-3d9777f59fb0
02-21 10:59:45.778  6862  6949 E BtGatt.ContextMap: remove() - removed: 57a1b35d-d97c-4818-bc5b-3d9777f59fb0
02-21 10:59:45.778 29476 30160 D BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
02-21 10:59:45.778 29476 30160 D BluetoothLeScanner: Registration failed, unregister scannerId = 0
02-21 10:59:45.778 29476 29476 D BluetoothLeScanner: Scan failed, reason: app registration failed
02-21 10:59:45.780 29476 29476 D BluetoothAdapter: STATE_ON
02-21 10:59:45.780 29476 29476 D BluetoothLeScanner: could not find callback wrapper
02-21 10:59:45.780 29476 29476 D Flic2ReactEvent: sendScanMessage() called with: event = [scanResult]
```

The scan completion results in error 3. How can we resolve this issue?

**Comment by jdegger** [comment]
Additionally, this happens almost immediately after starting the scan.

**Comment by jdegger** [comment]
Additionally additionally, we see that rebooting the phone fixes this issue as it probably resets the GATT registered clients. Question is, how does this happen in the first place?

**Comment by Emill** [comment]
So totally on the phone there can be 32 "gatt clients", which is either a Bluetooth LE scanner or a BluetoothGatt object. The scanner is usually freed correctly internally by the Android sdk but the BluetoothGatt objects must always be manually freed by calling `.close()` on them.

Which phones do you see this on? Do you have any other bluetooth apps running?

The flic2lib should do this correctly. I've seen sometime on some buggy Android version that when an app was killed the BluetoothGatt objects weren't properly cleared automatically by the system (which it should do).

**Comment by jdegger** [comment]
These phone are only used by our own app. There is not much else on the phone as they are only for development.

```
osName		Android
osVersion	9
name		Galaxy J4+
brand		samsung
model		msm8937
```

Our own app is also scanning for BTLE beacons, we will check if this is somehow registering GATT clients without calling `.close()`, but we expect this is not the case.

After Googling we also noticed there are some bugs in the OS itself causing this. This might be the case. If there is nothing you can do to resolve this on your side we will close this issue and check it ourselves.

Is it possible to catch this specific error and turn it in an error code on your end? As rebooting the phone works, it might be interesting this specifically instruct the user to do this when they encounter the 32 limit.

**Comment by Emill** [comment]
Doesn't the `onComplete` callback get invoked, with `result` = `Flic2ScanCallback.RESULT_FAILED_SCAN_ERROR` and `subCode` = `android.bluetooth.le.ScanCallback.SCAN_FAILED_APPLICATION_REGISTRATION_FAILED`?

**Comment by jdegger** [comment]
We might do, we just noticed we are not forwarding the subCode. We will make a ticket to add this to our library.

For now I will close this issue as it's probably nothing related to Flic.
