### ISSUE TITLE
Any way to reduce latency?

### ISSUE THREAD

**Issue by yosoycody** [50ButtonsEach/flic2lib-android#7]
I'm trying to get the down button action as soon as possible. Within the Flic2ButtonListener, I'm catching the down action within onButtonUpOrDown() function, but it seems to be pretty delayed. Any suggestions on how to reduce latency? In the iOS SDK, you have the button.triggerMode = .click option to speed it up.

**Comment by Emill** [comment]
If you listen to buttonDown, that should be equal to using triggerMode click.

The Bluetooth connection parameters are set here: https://github.com/50ButtonsEach/flic2lib-android/blob/7f7848b1d27acb2457c759c7f2caed2cd077a1f0/flic2lib-android/src/main/java/io/flic/flic2libandroid/Flic2Button.java#L804. You could try lowering the connection interval. Unfortunately those are not yet exposed in the public API.

**Comment by yosoycody** [comment]
So I guess currently there would be no way to lower the connection interval without modifying the library source?

**Comment by Emill** [comment]
Correct. Could you tell me a bit more about your use case where you need such a low latency?

**Comment by yosoycody** [comment]
We are working on a software product focused on capturing user inputs and measuring their response time in milliseconds so it is important to minimize latency in order for this product to be viable for our use case.   Also noting that for iOS we are not seeing any of the same latency with your SDK and buttons.

**Comment by Emill** [comment]
Try set the values to (12, 12, 125, 600). That should give you a latency of 15 ms. The lowest Android accepts is 11.25 ms (9 in units of 1.25 ms). To try that you should use the values (9, 9, 125, 600). 600 means timeout of 6 seconds.

**Comment by yosoycody** [comment]
Thanks I'll give that a try and report back results.

**Comment by yosoycody** [comment]
sendConnParamsUpdate(9, 9, 125, 600) worked great! it seems to have fixed the latency issue. does this have any negative effects (i.e. battery usage)? also, one other question regarding the SDK. For iOS, the buttons automatically re-connect when the scanner starts, after the app has been force quit. But with android, they never automatically re-connect when the app starts back up (after its been quit from either a crash, updated, force quit, etc.). I start the flic scan as soon as the app starts up, but there's no automatic re-connection. the only way to have them re-connect is to hold each button up to 10 secs again, as if I'm re-pairing. any ideas/suggestions?

**Comment by Emill** [comment]
Start scan is only used for pairing a new button. For connecting to existing buttons, you shall call connect() on the Flic2Button object, which will set up a pending connection so that it will connect whenever the button starts advertising.

And yes a low connection interval will drain the battery faster, especially if the button is far away from the phone (when there are many packet losses).

**Comment by yosoycody** [comment]
Within the Flic2ScanCallback, I am doing the button.connect() within the onDiscoveredAlreadyPairedButton(Flic2Button button) function. But still, the button's don't automatically connect after the app starts again without holding each button for several seconds.

**Comment by Emill** [comment]
As I mentioned, the scanner shall only be used when pairing new buttons. See https://github.com/50ButtonsEach/flic2lib-android-sample for a full example how to automatically connect when the app starts.

**Comment by yosoycody** [comment]
thanks!
