### ISSUE TITLE
Button provisioning?

### ISSUE THREAD

**Issue by weliem** [50ButtonsEach/flic2lib-android#8]
I am trying to work with some brand new buttons that come straight out of the box and have never been connected before to any app/hub. In the scanning code you look for the FLIC service UUID but by default the buttons don't advertise any service UUID nor any default name. It looks like I can only scan on mac address to find them...

I doublechecked with nrF Connect, and indeed no service UUID is advertised.

Can you provide clarity on how the initial 'provisioning flow' is supposed to work? I see the name can be set using the library but is that also true for the service UUID?

**Comment by Emill** [comment]
Hi.

The name that can be set is just an internal name that can later be read. It's not the Bluetooth name.

You are supposed to tell the user to hold down the button while scanning for buttons. After some seconds, the button will then start to advertise the Flic 2 service UUID. More info can be found here: https://github.com/50ButtonsEach/flic2-documentation.

See https://github.com/50ButtonsEach/flic2lib-android-sample for an example how to use this library.

**Comment by weliem** [comment]
Ahhhh...I see it now. I didn't realize there was a 'pairing mode'...thx
